### PR TITLE
Tidy up the code base

### PR DESCRIPTION
**Pull request by crtag**
Future-proof application configuration management via the taxonomy of settings.
Remove application configuration management methods into a separate module.

### CODE REVIEW

**Comment by maaku** [comment]
Code review looks good. I’ll look into why the CI builds are failing when I get back to a computer. Thanks for adding the fullscreen option storage.

**Comment by crtag** [comment]
@maaku 
I still want to add a few more things to this PR, so left it in the draft state and didn't run any format checkers etc, this might be a reason for fails. Not sure if it's possible to skip builds/checks for draft PRs.

Things I'd like to add is to revise the storage so it's a normal table with settings, potentially later can be introduced taxonomy so those could be configured from UI for example, and get the into configuration out of the main file as it will be growing and has to be as readable as possible.

**Comment by maaku** [comment]
No worries! I see the Draft setting. It wasn't so obvious when I was looking at the PR on my phone. Take your time to get it the way you want it.

FYI there's a check.sh script you can run in the root directory to do most of the CI checks that are run by GitHub actions.

**Comment by crtag** [comment]
@maaku There are some issues around `sqlite` and I will have a look later tomorrow at what that could be as I need to get docker/podman going. Otherwise, if you have any hints that would be much appreciated.

**Comment by crtag** [comment]
@maaku Sorted out cross-platform issues. This should wrap up generic app settings storage development and other basic app bootstrapping. The next step is adding actual CAD features.

**Comment by crtag** [comment]
Rebasing

**Pull request closed without merging**
