### PR TITLE
Support MRSimulation format. 

### PR DESCRIPTION
**Pull request by crtag**
Issue #35

### CODE REVIEW

**Comment by crtag** [comment]
Happy to wrap up this PR as it fully addresses the MRSIM format parser and paves the way to further development as outlined in https://github.com/atomCAD/atomCAD/issues/35#issue-1894280169

**Comment by philipturner** [comment]
Great work! Next steps might be the "MRSimulation 2.0" binary codec, which replaces the Apple-specific LZBITMAP with a GPU-accelerated lossless compressor. That will probably be supported after a plugin for my codebase is integrated, instead of re-implementing from scratch in Rust.

**Comment by crtag** [comment]
> Great work! Next steps might be the "MRSimulation 2.0" binary codec, which replaces the Apple-specific LZBITMAP with a GPU-accelerated lossless compressor. That will probably be supported after a plugin for my codebase is integrated, instead of re-implementing from scratch in Rust.

> You should look at the literature for mesh compression, specifically those that support compressing animations.

@maaku @philipturner 

I'm unsure if this is critical at the present stage. Is the number of atoms per simulation/rendering is expected to be orders higher, or simulation timeframe significantly longer, or both? I might also have missed some messages in Discord, so it could be a good idea to refresh/summarize short-term goals?

Anyhow, if mrsim-text can be rendered in AtomCAD, or for that matter any other simulation format until AtomCAD becomes fully end-2end suite this looks like a win. I'd stick to the original plan to get this scenario implemented, and this can be scaled later as necessary. 

Are there any obvious issues preventing this PR merge?

**Comment by philipturner** [comment]
> I'm unsure if this is critical at the present stage. Is the number of atoms per simulation/rendering is expected to be orders higher, or simulation timeframe significantly longer, or both? I might also have missed some messages in Discord, so it could be a good idea to refresh/summarize short-term goals?

It's not really critical at the current stage, but something to think about in the future. As I start making million-atom simulations whose sizes ranges in several gigabytes, which must be transferred over the internet in a reasonable time frame. Conventional ZIP compressing of something so large would take minutes.

**Comment by crtag** [comment]
> > I'm unsure if this is critical at the present stage. Is the number of atoms per simulation/rendering is expected to be orders higher, or simulation timeframe significantly longer, or both? I might also have missed some messages in Discord, so it could be a good idea to refresh/summarize short-term goals?
> 
> It's not really critical at the current stage, but something to think about in the future. As I start making million-atom simulations whose sizes ranges in several gigabytes, which must be transferred over the internet in a reasonable time frame. Conventional ZIP compressing of something so large would take minutes.

Yes, this needs benchmarking work. 99% of the data are ASCII numbers and spaces, it should compress extremely well with dictionary-based methods. If real-time simulation streaming ever comes up it would require a slightly different format anyway.

**Comment by maaku** [comment]
I wouldn’t mind an explanation of the goals of this PR either, to be honest. I’m not sure I understand correctly what it is intended to be doing.On Oct 12, 2023, at 1:24 AM, Alexey Novikov ***@***.***> wrote:﻿

Great work! Next steps might be the "MRSimulation 2.0" binary codec, which replaces the Apple-specific LZBITMAP with a GPU-accelerated lossless compressor. That will probably be supported after a plugin for my codebase is integrated, instead of re-implementing from scratch in Rust.


You should look at the literature for mesh compression, specifically those that support compressing animations.

@maaku @philipturner
I'm unsure if this is critical at the present stage. Is the number of atoms per simulation/rendering is expected to be orders higher, or simulation timeframe significantly longer, or both? I might also have missed some messages in Discord, so it could be a good idea to refresh/summarize short-term goals?
Anyhow, if mrsim-text can be rendered in AtomCAD, or for that matter any other simulation format until AtomCAD becomes fully end-2end suite this looks like a win. I'd stick to the original plan to get this scenario implemented, and this can be scaled later as necessary.
Are there any obvious issues preventing this PR merge?

**Comment by philipturner** [comment]
Dictionary-based compression methods are extremely slow for this kind of data. We’re talking 10-100x slower than it theoretically could be, and the fastest dictionary-based method (i.e. usable with real-time with near-optimal compression ratio), LZBITMAP, is not cross-platform. So it’s quite difficult to create a cross-platform solution with reasonable performance for real-time decompression ATM.

The purpose of this PR is a first step toward being able to use simulation trajectories I create, inside of atomCAD. And eventually, for people without a Mac, a means to render simulations from OpenMM/MM4. As of now that’s a major hurdle to cross-platform support for MM4, and Python-based scripted applications like Vim can’t handle the 120 FPS simulation data in real-time. The dominant use case for those apps is static data without a time dimension, which has ~1200x less data volume with the same amount of atoms.

Although the strained shell bearing example isn’t “a very large number of atoms”, that’s because it’s the smallest edge case I could find. Only 2000 atoms and a few seconds. Most other examples I have hosted are much larger, to the point where the sheer volume of data is a massive bottleneck. Right now the decoding speed of the text decoder seems sufficient to load these with around 1 second latency, a major accomplishment given some benchmarks provided in the previous (closed) pull request. It should now be possible to view ~30,000 atom simulations with 1200 frames in atomCAD, with reasonable startup latency. Which was the goal of the MRSim-Txt format. Having any ability to load cross-platform, even if not optimal, is better than an MRSim-Binary format that’s too complex for anyone to port this early on.

**Comment by philipturner** [comment]
To quantify some of the data volumes, 30000 atoms * 10000 frames = 30 million. With 12 bytes/atom (3 x Float32), that's 360 MB without compression. You can easily see how that will reach gigabytes with 1,000,000 atoms enabled by multi-GPU simulators. Also the compression speed of existing single-core ZIP compressors is worse than the bandwidth of a USB 2.0 flash drive.

One long-term end goal, with MRSim as a whole, is removing the need to load an entire trajectory in RAM at once. The "MRSimulation 2.0" format I talk about can be streamed in bits from SSD, similar to a how a video is streamed from a server. That also demands real-time decompression of 1,000,000 atom coordinates in far less than 1 millisecond on consumer PCs. This requires a more efficient and portable lossless compressor than ZIP or potentially LZBITMAP too. The GPU OpenCL code for that, I'm not sure whether we want to write that in Rust, inside the atomCAD codebase initially. That's what I was explaining above.

Until any of that comes to fruition, getting the lower-performance text-based codec is a good first-step, and something that satisfies a pressing need in the here and now.

**Comment by crtag** [comment]
@maaku Also, the plan outlined in the starter message: https://github.com/atomCAD/atomCAD/issues/35

**Comment by philipturner** [comment]
I think it's quite certain this PR won't be merged. The repo owner is mischaracterizing a geometry based compressor, saying it isn't mesh compressed or maximally efficient, then using that as the excuse. It may be a good official reason to back it up, although a lousy one at that. There could be a more straightforward means of expressing that you don't want this feature in atomCAD. It is clear that $O(n)$ timestepping MD simulation is not considered the most important validation mechanism.

Anyway, Molecular Renderer is now a competitor to atomCAD, and allied with MSEP whenever applicable. I'll still make my APIs open and usable to other programs. MRSimulation got a text format that could be parsed in Python. MM4 will get proper C and Python bindings, making it easy to integrate into existing Python scripting workflows (like Tom's). I doubt any people besides myself and Alexis will use the tools I create, but they're there and open if you wish to.

**Comment by maaku** [comment]
There is no need for hostility. I wish you the best on your project.

atomCAD will not be taking on a maintenance burden for a feature that is not on our roadmap and only exists to facilitate a competing project. I am closing this PR and the related issue as won’t-fix.

**Pull request closed without merging**
